# Generated by Django 5.1.2 on 2024-10-29 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('water_retention_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('permeability_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('area_size', models.FloatField(default=0)),
                ('soil_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands', to='SoilType.soiltype')),
            ],
        ),
    ]
