# Generated by Django 4.1 on 2024-10-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type_name', models.CharField(max_length=100)),
                ('winter_irrigation_frequency', models.CharField(max_length=20)),
                ('spring_irrigation_frequency', models.CharField(max_length=20)),
                ('summer_irrigation_frequency', models.CharField(max_length=20)),
                ('fall_irrigation_frequency', models.CharField(max_length=20)),
            ],
        ),
    ]
