# Generated by Django 4.1 on 2024-10-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IrrigationSchedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sunlight_requirements', models.CharField(max_length=100)),
                ('water_needs', models.CharField(max_length=100)),
                ('growth_rate', models.CharField(max_length=100)),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='IrrigationSchedule.planttype')),
            ],
        ),
    ]
