# Generated by Django 4.1 on 2024-10-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrrigationSchedule', '0002_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='plant_type_image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_types/'),
        ),
    ]
