# Generated by Django 4.1 on 2024-10-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrrigationSchedule', '0003_planttype_plant_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/irrigation/'),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='plant_type_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/irrigation/'),
        ),
    ]
