# Generated by Django 4.1 on 2024-10-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
