# Generated by Django 4.1 on 2024-10-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAPP', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_amount', models.FloatField(help_text='Water amount in liters needed based on current weather.')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly')], default='daily', help_text='Frequency of irrigation based on weather data.', max_length=50)),
                ('start_time', models.TimeField(help_text='Time of day to start irrigation.')),
                ('duration', models.IntegerField(help_text='Duration of irrigation in minutes.')),
                ('weather_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_plan', to='weatherAPP.weatherdata')),
            ],
            options={
                'verbose_name': 'Irrigation Plan',
                'verbose_name_plural': 'Irrigation Plans',
            },
        ),
    ]
