# Generated by Django 4.1 on 2024-10-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the crop', max_length=30)),
                ('water_need', models.DecimalField(decimal_places=2, help_text='Amount of water required per day (liters)', max_digits=5)),
                ('growth_stage', models.CharField(max_length=50)),
                ('optimal_temperature', models.CharField(help_text='Ideal temperature range for the crop (e.g., 18-25°C)', max_length=50)),
            ],
        ),
    ]
