# Generated by Django 4.1 on 2024-10-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soilCropRecommender', '0002_field_alter_crop_name_alter_crop_optimal_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='soilCropRecommender.crop'),
        ),
    ]
