# Generated by Django 4.1 on 2024-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilCropRecommender', '0004_prediction_alter_field_soil_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='soil_quality',
            field=models.CharField(choices=[('DRY', 'DRY'), ('HUMID', 'HUMID'), ('WET', 'WET')], default='DRY', max_length=50),
        ),
    ]
