# Generated by Django 5.1.2 on 2024-10-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilCropRecommender', '0005_alter_field_soil_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('water_retention_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('permeability_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soilCropRecommender.soiltype')),
            ],
        ),
    ]
