# Generated by Django 5.1.2 on 2024-10-29 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilCropRecommender', '0006_soiltype_land'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='area',
        ),
        migrations.RemoveField(
            model_name='land',
            name='name',
        ),
        migrations.AddField(
            model_name='land',
            name='area_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='land',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='land',
            name='soil_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands', to='soilCropRecommender.soiltype'),
        ),
    ]
